language: javascript
# 分支
branches:
  only:
    - main # 构建的分支
# 缓存
cache:
  directories:
    - node_modules # 依赖缓存的目录
# 安装命令
install:
  - npm install --registry=https://registry.npm.taobao.org
  - npm run build:dev
# 执行脚本
script:
  - npm run build:dev
